application: hypowwdchat
version: 1
runtime: python
api_version: 1

handlers:
- url: /say.*
  script: main.py

- url: /update.*
  script: main.py

- url: /
  static_files: index.html
  upload: index.html
